### ISSUE TITLE
`Print` is processed as `Printf` call

### ISSUE THREAD

**Issue by vblz** [go-pkgz/lgr#20]
### Way to reproduce
```go
package main

import (
	"github.com/go-pkgz/lgr"
)

func main() {
	const line = "https%3A%2F%2Ftest.test"
	lgr.Print(line)
}
```
### Result
`2020/10/06 22:06:37 INFO  https%!A(MISSING)%!F(MISSING)%!F(MISSING)test.test`
### Expected result
`2020/10/06 22:06:37 INFO  https%3A%2F%2Ftest.test`

### Comparision with standard log package
This issue also affects `lgr.ToStdLogger`
#### More explained example
```golang
package main

import (
	"github.com/go-pkgz/lgr"
	"log"
	"os"
)

func main() {
	const line = "https%3A%2F%2Ftest.test"
	log.SetOutput(os.Stdout)

	lgr.Print(line)
	lgr.Printf(line)
	lgr.ToStdLogger(lgr.Default(), "").Print(line)

	log.Print(line)
	log.Printf(line)
	log.New(os.Stdout, "", 0).Print(line)
}
```
#### Results
```
2020/10/06 22:08:26 INFO  https%!A(MISSING)%!F(MISSING)%!F(MISSING)test.test
2020/10/06 22:08:26 INFO  https%!A(MISSING)%!F(MISSING)%!F(MISSING)test.test
2020/10/06 22:08:26 INFO  https%!A(MISSING)%!F(MISSING)%!F(MISSING)test.test
2020/10/06 22:08:26 https%3A%2F%2Ftest.test
2020/10/06 22:08:26 https%!A(MISSING)%!F(MISSING)%!F(MISSING)test.test
https%3A%2F%2Ftest.test
```

**Comment by umputun** [comment]
thx for the report. I have committed the fix, pls see if the current master resolves your issue.

**Comment by vblz** [comment]
Thank you for so fast reply.

The issue has been fixed, but created another one: no warnings in `Printf` method if args are missed.

The output of More explained example
```
2020/10/06 22:27:43 INFO  https%3A%2F%2Ftest.test
2020/10/06 22:27:43 INFO  https%3A%2F%2Ftest.test
2020/10/06 22:27:43 INFO  https%3A%2F%2Ftest.test
2020/10/06 22:27:43 https%3A%2F%2Ftest.test
2020/10/06 22:27:43 https%!A(MISSING)%!F(MISSING)%!F(MISSING)test.test
https%3A%2F%2Ftest.test
```

**Comment by umputun** [comment]
well, I'm not sure how to resolve this without adding the `Log` method to the interface, which I really don't want to do. To me, this feels like an acceptable trade-off but if you have any ideas on how to address it without interface change pls share.

**Comment by vblz** [comment]
It might be important when you want to use lgr with another packages. They get standard logger and call `Print` method with that kind of strings which cause problems in logs.

As an option I can see now it is possible to use an internal interface different from `L`  inside the package.

**Comment by umputun** [comment]
I don't think the new interface (in addition to `log.L`) will be an adequate solution for such a minor issue.
