### ISSUE TITLE
Log with level "ERROR" puts a message into stdout twice

### ISSUE THREAD

**Issue by egregors** [go-pkgz/lgr#21]
For some reason `log.Printf("[ERROR] oh no!")` puts error into stdout twice by default. 

main.go
```go
package main

import log "github.com/go-pkgz/lgr"

func main() {
	log.Printf("[ERROR] oh no!")
}
```

output
```shell
➜  _ git:(master) ✗ go run main.go
2021/01/28 12:11:29 ERROR oh no!
2021/01/28 12:11:29 ERROR oh no!
```

Maybe I am doing something wrong?

**Comment by umputun** [comment]
I don't think it pritns both to stdout. It should print to stdout and stderr

**Comment by egregors** [comment]
Got it. Sorry, my bad :/
