### ISSUE TITLE
Caller reporting

### ISSUE THREAD

**Issue by zonescape** [go-pkgz/lgr#8]
My recent [PR](https://github.com/go-pkgz/lgr/pull/5) shows that I probably don't understand your intent. Correct me if I am wrong.

### Logger usage:

- a package that needs logging must declare the interface:
```Go
type L interface {
	Logf(format string, args ...interface{})
}
```
- some code **outside** of the package creates and configures an instance of `lgr.Logger` (including ignored callers)
- the instance of `lgr.Logger` is passed to the package

### Caller filtering:
- based on function level (we filter functions and not packages as it currently implied). Example setup code:
```Go
lgr.Setup(lgr.CallerIgnore("github.com/umputun/remark/backend/app/rest.errDetailsMsg", "github.com/umputun/remark/backend/app/rest.SendErrorJSON"))
```
- this filtering works irrespective of the logged caller info type (whether it `CallerFile` or `CallerFunc` or `CallerPkg`). Currently some "filtering" is done only if `l.callerPkg && !l.callerFile && !l.callerFunc` equals `true`.

Also in #2 you [mention](https://github.com/go-pkgz/lgr/pull/2#issuecomment-471024425) that below log record is incorrect (this record is generated by Remark42 if we execute command `http :8080/auth` having logger replaced to the new one from the master branch):
```
2019/03/08 04:58:17.446 [INFO]  {logger/logger.go:120} GET - /auth - 0c10a2713542 - 400 (36) - 93.542µs
```
It literally says that [`(*Logger).Logf()`](https://github.com/go-pkgz/lgr/blob/a7f793bd4672a4a9faf7c6bd37545dff0082bdda/logger.go#L53) method is called from [`github.com/go-pkgz/rest/logger/logger.go:120`](https://github.com/go-pkgz/rest/blob/d8ef3d312b712d5a73a92a12451b6917923e8560/logger/logger.go#L120) which is truth. Why do you think that this record is incorrect? What record would you prefer to see? Don't you mix up `github.com/go-pkgz/lgr` and `github.com/go-pkgz/rest/logger` packages?

**Comment by umputun** [comment]
there are two distinct cases related to the caller reporting:

1. indirect logging handling by user's package. For example [this use-case](https://github.com/umputun/remark/blob/master/backend/app/rest/httperrors.go#L45)
1. indirect logging via http middleware or any other middleware-like decorators

Case 1 seems to be clear, and this is about the ability to skip wrapper function as frame-related things (caller file, line, pkg) reported. Your example with "rest.errDetailsMsg" shows this usage.

Case 2 not that clear. To demonstrate it I have created a logger like this one:

```
	lg := log.Func(func(format string, args ...interface{}) {
		fmt.Printf(format+"\n", args...)
		debug.PrintStack()
	})
```

and passed it to rest's logger, i.e. `ropen.Use(logger.New(logger.Log(lg), logger.WithBody,
				logger.Prefix("[INFO]"), logger.IPfn(ipFn)).Handler)`

The produced result on http call:

```
[INFO] GET - /api/v1/find?site=remark&sort=-controversy&format=tree&url=https://radio-t.com/p/2018/07/14/podcast-606/ - 8e228e9cfeca - 200 (115) - 301.426µs
goroutine 25 [running]:
runtime/debug.Stack(0x9e, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/umputun/remark/backend/app/rest/api.(*Rest).routes.func4(0x17517bc, 0x2, 0xc000095810, 0x1, 0x1)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/app/rest/api/rest.go:201 +0xbb
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/lgr.Func.Logf(0x1780b38, 0x17517bc, 0x2, 0xc000095810, 0x1, 0x1)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/lgr/interface.go:19 +0x58
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/logger.(*Middleware).Handler.func1.1(0xc000180200, 0xc000522190, 0xc0004941a0, 0xbf1d0d3be4572d48, 0x478dbc4fd, 0x1d1a0a0, 0x0, 0x0, 0x0, 0x0)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/logger/logger.go:120 +0xa34
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/logger.(*Middleware).Handler.func1(0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/logger/logger.go:124 +0x1b5
net/http.HandlerFunc.ServeHTTP(0xc0005105e0, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/auth/middleware.(*Authenticator).auth.func1(0x183f120, 0xc0005105e0, 0x184a1e0, 0xc000456540, 0xc000180200, 0x183dcc0, 0xc000494180)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/auth/middleware/auth.go:61 +0x14d
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/auth/middleware.(*Authenticator).auth.func2.1(0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/auth/middleware/auth.go:80 +0x7e2
net/http.HandlerFunc.ServeHTTP(0xc000512630, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/didip/tollbooth_chi.(*limiterWrapper).ServeHTTP(0xc000510640, 0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/didip/tollbooth_chi/tollbooth_chi.go:41 +0x2b5
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc00051be40, 0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/chain.go:31 +0x52
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc00051c1e0, 0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/mux.go:424 +0x27f
net/http.HandlerFunc.ServeHTTP(0xc000520200, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00051c1e0, 0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/mux.go:69 +0x451
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*Mux).Mount.func1(0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/mux.go:291 +0x127
net/http.HandlerFunc.ServeHTTP(0xc000511c80, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc00051c0c0, 0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/mux.go:424 +0x27f
net/http.HandlerFunc.ServeHTTP(0xc0005200c0, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/cors.(*Cors).Handler.func1(0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/cors/cors.go:199 +0x183
net/http.HandlerFunc.ServeHTTP(0xc000510160, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest.Ping.func1(0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/middleware.go:39 +0x1f1
net/http.HandlerFunc.ServeHTTP(0xc000510180, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest.AppInfo.func1.1(0x184a1e0, 0xc000456540, 0xc000180200)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/middleware.go:22 +0x3ba
net/http.HandlerFunc.ServeHTTP(0xc0005220f0, 0x184a1e0, 0xc000456540, 0xc000180200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/middleware.Timeout.func1.1(0x184a1e0, 0xc000456540, 0xc000180100)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/middleware/timeout.go:44 +0x17a
net/http.HandlerFunc.ServeHTTP(0xc0005101a0, 0x184a1e0, 0xc000456540, 0xc000180100)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/middleware.(*throttler).ServeHTTP(0xc0005120f0, 0x184a1e0, 0xc000456540, 0xc000180100)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/middleware/throttle.go:94 +0x32c
github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest.Recoverer.func1.1(0x184a1e0, 0xc000456540, 0xc000180100)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/middleware.go:55 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc000512120, 0x184a1e0, 0xc000456540, 0xc000180100)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/middleware.RealIP.func1(0x184a1e0, 0xc000456540, 0xc000180100)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/middleware/realip.go:34 +0x99
net/http.HandlerFunc.ServeHTTP(0xc0005101c0, 0x184a1e0, 0xc000456540, 0xc000180100)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00051c0c0, 0x184a1e0, 0xc000456540, 0xc000180000)
        /Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/github.com/go-chi/chi/mux.go:81 +0x294
net/http.serverHandler.ServeHTTP(0xc0002c6a90, 0x184a1e0, 0xc000456540, 0xc000180000)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000de280, 0x184c420, 0xc00026e0c0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:2884 +0x2f4
```

the problem here - which frame should we report as a caller? Generally, the user doesn't care about the internals of our logger(s) and would like to see a reference to his code handled the request, or at least as close as possible to his call. In this case it will be `api.findCommentsCtrl`. However, there is no `api.findCommentsCtrl` in the stack above and there is nothing good we can report here. So, based on this trace I don't see how we can report some useful caller info here unless I missed smth.

> Don't you mix up github.com/go-pkgz/lgr and github.com/go-pkgz/rest/logger packages?
Hmm, not sure how `rest/logger` is even related to this. It has nothing to do with caller info, but the message itself.

**Comment by zonescape** [comment]
OMG, Umputun, I third time tell you - there is a caller on the stack! It still the same:
```
github.com/umputun/remark/backend/vendor/
    github.com/go-pkgz/rest/logger.(*Middleware).Handler.func1.1()

/Users/umputun/go-home/src/github.com/umputun/remark/backend/vendor/
    github.com/go-pkgz/rest/logger/logger.go:120
```

`api.(*Rest).findCommentsCtrl()` is not a caller of the logging interface's `Logf()` method. And of course it is absent on the stack because it is called from the same function as `logger.(*Middleware).Handler.func1.1()` but before it.

If I understand you correctly what you want is not a caller in terms of call stack but the final HTTP request handler that triggers response writing. That information can be obtained but this is not related to `lgr.Logger`.

**Comment by umputun** [comment]
Not sure what exactly your point here. Are you saying this caller is helpful in some way for the user? Well, it is a caller, and it is technically correct one, but it has 0 useful information. As I said above - in this case, we don't have anything useful to show. Filtering/skipping any levels adds nothing useful to the caller info. We can show `logger/logger.go`, or `logger.(*Middleware).Handler.func1.1()` or even `http/server.go` - it makes no difference at all as this info as useful as showing "blah"

**Comment by zonescape** [comment]
OK I hope I get it finally. Maybe we should add one more option to hide some callers?
```Go
// HideCallers sets callers for which caller info will not be displayed
func HideCallers(hiddenCallers ...string) Option {}
```

Setup code:
```Go
lgr.Setup(lgr.HideCallers(
	"github.com/umputun/remark/backend/vendor/github.com/go-pkgz/rest/logger.(*Middleware).Handler.func1.1",
))
```

Example log message:
```
2019/03/08 04:58:17.446 [INFO]  GET - /auth - 0c10a2713542 - auth.(*Service).Handlers.func1 - 400 (36) - 93.542µs
```

Note that in the above message I add info about the handler that triggers response writing (currently unimplemented feature).

If you appreciate the changes then I can write both PRs:
- `lgr`: implementing `CallerIgnore` and `HideCallers`
- `rest/logger`: implementing logging of handler info

**Comment by umputun** [comment]
I'm trying to figure out why both `CallerIgnore` and `HideCallers` needed. `CallerIgnore` supposed to be the one to set a list of matches. Those matches should be ignored/hidden completely, i.e. exactly like you described in the "Caller filtering" section. I think you meant to hide callers literally, for non-ignored frames, i.e. remove {caller info} from the final msg. It this correct - I don't think such functionality needed. And for sure, having both Hide and Ignore around callers will be extremely confusing.

The part about making `rest/logger` aware of handler's info is not really related to this ticket or even to lgr module. I can think of some loosely coupled ways to communicate extras into lgr from a middleware call, but it will involve some support of #6 . So, let's drop this part for now.

_Pls note - I didn't have any problem with the original proposal, just tried to describe is why middleware logging wasn't too helpful in real life._

**Comment by zonescape** [comment]
> I think you meant to hide callers literally, for non-ignored frames, i.e. remove {caller info} from the final msg.

Yes, I meant exactly this.

Note that as far as I can see you don't use modules for the local builds. This may lead to the subtle problems when using function skipping for vendored packages because func names may differ. For example, func name when vendoring without modules:
```
"github.com/umputun/remark/backend/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP"
```
with modules:
```
"github.com/go-chi/chi.(*Mux).ServeHTTP"
```

**Comment by zonescape** [comment]
The algorithm in #10 looks quite complex and magical. May be we should change the `L` interface to the one I described in #5?
```Go
type L interface {
	Logf(format string, args ...interface{})
	LogfForDepth(calldepth int, format string, args ...interface{})
}
```
You said that it is exotic. I disagree with you because there is a similar method in the standard logger. Namely [`(*Logger).Output(calldepth int, s string)`](https://golang.org/pkg/log/#Logger.Output).

I also can propose another logging interface:
```Go
type L interface {
	Logf(format string, args ...interface{})
	// ForDepth returns logger configured to log callers
	// located calldepth deeper in the stack then the caller
	// of the returned logger's Logf() method.
	ForDepth(calldepth int) L
}
```
Again, clients that don't want to log deep callers can use short form of the interface (the current one), the clients that do want this logging can use an extended form.

**Comment by umputun** [comment]
I agree about the complexity and I have a strong feeling we went the wrong direction with the recent changes and extensions. The primary goal why I even made this package, was to make some minimal, no-bs logger with necessary functionality only. 

The part of `Logf` only interface is the fundamentally minimum contract I want to keep. It has several technical advantages, like the ability to provide simple implementations, the ability to use functional wrappers and it communicates the intent very well. 

>  there is a similar method in the standard logger. 

well, it doesn't make the case any more convincing to me :) IMHO standard logger design sucks and this is one of the main reasons why we (and many others) trying to make a better one.

> ForDepth(calldepth int) L

I think this is even worse. Factory method inside of interface returning the interface gets dangerously close to spring's abuse of abstract factories. 

> clients that don't want to log deep callers can use short form of the interface

It is only partially correct. For example, by introducing LogfForDepth/ForDepth we are effectively enforcing this extended contract to all lazy users with default loggers. We also break compatibility with `lgr.Func`. And, the most important thing - the moment user calls/uses `LogfForDepth` he immediately gets too coupled with lgr. I want to avoid all of this, especially for such a minor function.

So, these are my suggestions:

1. drop the idea of ignored stack frames completely. 
1. add (actually restore) `skip` parameter 
1. expose `skip` setter as a functional option
1. set "skip" to 2 by default and 3 for pre-constructed (`Default()`)logger

From consumer's POV regular logger and a logger for special cases (like calls from a wrapper function) will be two different loggers created with different `skip` options.

**Comment by zonescape** [comment]
I give up. This issue may be closed.
